add PartialEq impl
eihwaz/bit-long-vec pull request #3
Opened 2020-01-10 16:31 UTC by joseildofilho

Hi There, 
I'm using your lib to a university project, so a feel that was a good idea to pull my changes, hope you like.

2020-01-10 20:27 UTC, vaIgarashi requested changes
Hello! Thanks for submiting your pull request. I have added some comments. It's possible to implement `PartialEq` automaticly using derive:  `#[derive(Debug, PartialEq, Eq)]`. You can also remove tests because it's not neccesery to test rust internals

2020-01-10 20:27 UTC, vagola commented on src/lib.rs
> +impl PartialEq for BitLongVec {
Why do we need manual trait implementation? We can use `#[derive(PartialEq)]`.

2020-01-10 20:27 UTC, vagola commented on src/lib.rs
> +    assert_eq!(vec, vec2);
It would be better to expect correct condition withouth panic.

```rust
assert!(vec != vec2);
```

2020-01-10 20:47 UTC, vagola commented on src/lib.rs
> +    assert_eq!(vec, vec2);
or `assert_ne!(vec, vec2)`

2020-01-13 22:59 UTC, joseildofilho commented
I belive that now it's in a movre "Rustic" way ? 
P.S.: I'm new in rust, somethings arent totally clear, but i really appreciate your suggesttion

2020-01-13 23:19 UTC, vaIgarashi approved these changes

2020-01-13 23:19 UTC, merged